export const ADD_CART = 'ADD_CART'    //加入购物车
export const EMPTY_CART = 'EMPTY_CART'  //清空购物车
export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const RECORD_SUGGESTION = 'RECORD_SUGGESTION'
export const REDUCE_CART = 'REDUCE_CART'
export const RECORD_DELIVERY_ADDRESS = 'RECORD_DELIVERY_ADDRESS'
export const RECORD_RESTAURANT = 'RECORD_RESTAURANT'
export const UPDATE_CART = 'UPDATE_CART'  //页面刷新时 更新购物车信息
export const LOCATION_READY = 'LOCATION_READY'  // 拉取餐馆信息
